const data = [
    "Students" = [
        {
            "student_id": 1,
            "name": "John Doe",
            "age": 25,
            "email": "johndoe@example.com",
            "password": "password123",
        },
        {
            "student_id": 2,
            "name": "Jane Doe",
            "age": 24,
            "email": "janedoe@example.com",
            "password": "password456",
        },
        {
            "student_id": 3,
            "name": "John Smith",
            "age": 26,
            "email": "johnsmith@example.com",
            "password": "password789",
        }
    ],
    "Faculty" = [
        {
            "faculty_id": 1,
            "Name": "Dr. Birmohan Singh",
            "Designation": "Professor",
            "Department": "Computer Science & Engineering",
            "Qualification": "Ph.D., M.E.",
            "email": "drbirmohansingh@gmail.com",
            "password": "password123",
        },
        {
            "faculty_id": 2,
            "name": "Dr. Damanpreet Singh",
            "Designation": "Professor",
            "Department": "Computer Science & Engineering",
            "Qualification": "Ph.D.,  M.Tech, B.Tech.",
            "email": "drdamanpreetsingh@gmail.com",
            "password": "password123",
        },
        {
            "faculty_id": 3,
            "name": "Dr. Major Singh Goraya",
            "Designation": "Professor",
            "Department": "Computer Science & Engineering",
            "Qualification": "Ph.D.,  M.Tech, B.Tech.",
            "email": "drmajorsinggorayah@gmail.com",
            "password": "password123",
        },
        {
            "faculty_id": 4,
            "name": "Dr. Manoj Sachan ",
            "Designation": "Professor",
            "Department": "Computer Science & Engineering",
            "Qualification": "Ph.D.,  M.E, B.Tech.",
            "email": "drmanojsachan@gmail.com",
            "password": "password123",
        },
        {
            "faculty_id": 5,
            "name": "Dr. Gurjinder Kaur",
            "Designation": "Associate Professor",
            "Department": "Computer Science & Engineering",
            "Qualification": "Ph.D.,  M.S, B.E.",
            "email": "drgurjinderkaur@gmail.com",
            "password": "password123",
        },
        {
            "faculty_id": 6,
            "name": "Dr. Amar Nath",
            "Designation": "Assistant Professor",
            "Department": "Computer Science & Engineering",
            "Qualification": "Ph.D.,  M.Tech, B.Tech.",
            "email": "dramarnath@gmail.com",
            "password": "password123",
        },
        {
            "faculty_id": 7,
            "name": "Dr. Jagdeep Singh",
            "Designation": "Assistant Professor",
            "Department": "Computer Science & Engineering",
            "Qualification": "Ph.D.,  M.Tech, B.Tech.",
            "email": "drjagdeepsingh@gmail.com",
            "password": "password123",
        },
        {
            "faculty_id": 8,
            "name": "Dr. Manminder Singh",
            "Designation": "Assistant Professor",
            "Department": "Computer Science & Engineering",
            "Qualification": "Ph.D.,  M.Tech, B.Tech.",
            "email": "drmanmidersingh@gmail.com",
            "password": "password123",
        },
        {
            "faculty_id": 9,
            "name": "Dr. Preetpal Kaur Buttar",
            "Designation": "Assistant Professor",
            "Department": "Computer Science & Engineering",
            "Qualification": "Ph.D",
            "email": "drpreetpalkaurbuttar@gmail.com",
            "password": "password123",
        },
        {
            "faculty_id": 10,
            "name": "Dr. Tajinder Singh",
            "Designation": "Assistant Professor",
            "Department": "Computer Science & Engineering",
            "Qualification": "Ph.D",
            "email": "drtajindersingh@gmail.com",
            "password": "password123",
        },
        {
            "faculty_id": 11,
            "name": "Dr. Utkarsh",
            "Designation": "Assistant Professor",
            "Department": "Computer Science & Engineering",
            "Qualification": "Ph.D.,  M.Tech, B.Tech.",
            "email": "drutkarsh@gmail.com",
            "password": "password123",
        },
        {
            "faculty_id": 13,
            "name": "Dr. VINOD KUMAR VERMA",
            "Designation": "Assistant Professor",
            "Department": "Computer Science & Engineering",
            "Qualification": "Ph.D",
            "email": "drvinodkumarverma@gmail.com",
            "password": "password123",
        },
        {
            "faculty_id": 14,
            "name": "Jaspal Singh",
            "Designation": "Assistant Professor",
            "Department": "Computer Science & Engineering",
            "Qualification": "M.E",
            "email": "jaspalsingh@gmail.com",
            "password": "password123",
        },
        {
            "faculty_id": 15,
            "name": "Rahul Gautam",
            "Designation": "Assistant Professor",
            "Department": "Computer Science & Engineering",
            "Qualification": "M.Tech, B.Tech.",
            "email": "rahulgautam@gmail.com",
            "password": "password123",
        },
    ],
    "Sessions" = [
        {
            "session_id": 1,
            "session_name": "Session 1",
            "session_date": "2021-01-01",
            "session_time": "10:00:00",
            "session_duration": 60,
            "session_location": "Location 1",
            "faculty_id": 1,
            "student_id":1,
        },
        {
            "session_id": 2,
            "session_name": "Session 2",
            "session_date": "2021-01-02",
            "session_time": "11:00:00",
            "session_duration": 60,
            "session_location": "Location 2",
            "faculty_id": 2,
            "student_id":2,
        },
        {
            "session_id": 3,
            "session_name": "Session 3",
            "session_date": "2021-01-03",
            "session_time": "12:00:00",
            "session_duration": 60,
            "session_location": "Location 3",
            "faculty_id": 3,
            "student_id":3,
        }],
]

export default data;